language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.1
    - android-14
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

#-----------------------------------
#COMMON PROPERTIES

branches:
  only:
    - master