language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.1
    - android-21
    - addon
    - extra
    #- sys-img-x86_64-android-21

licenses:
  - android-sdk-license-.+

#-----------------------------------
#COMMON PROPERTIES

branches:
  only:
    - master